/**
 * Provider registry.
 *
 * The shell must be able to ask "is Instagram connected?" today, before anyone
 * has written an Instagram integration. The registry answers honestly: until a
 * feature engineer registers a real implementation, every capability reports
 * `unavailable('not_connected', ...)`.
 *
 * This is NOT a mock and NOT fake API behaviour. It never returns invented
 * data, never fabricates success, and never pretends a network call happened.
 * It reports the literal truth: nothing is wired up yet.
 *
 * HOW A FEATURE ENGINEER USES THIS
 * --------------------------------
 * In your feature's entry point (e.g. `features/social/register.ts`):
 *
 *     import { registerProvider } from '@/lib/providers/registry';
 *     import { instagramProvider } from './providers/instagram';
 *     registerProvider('instagram', instagramProvider);
 *
 * Then call it once from `features/social/index.ts`. Do not edit this file to
 * add your provider - registration is a runtime call, so no two engineers ever
 * touch the same line.
 */

import { unavailable, type DataState } from '@/lib/state/DataState';
import type { ProviderId } from '@/types/domain';
import type { ConnectableProvider } from './contracts';
import type { ConnectionInfo } from './types';

const NOT_CONNECTED_MESSAGE =
  'This account has not been connected yet. Connect it to see real data here.';

/** Display names used by the shell before any provider registers itself. */
const DISPLAY_NAMES: Record<ProviderId, string> = {
  google_business: 'Google Business Profile',
  instagram: 'Instagram',
  facebook: 'Facebook',
  linkedin: 'LinkedIn',
};

const registry = new Map<ProviderId, ConnectableProvider>();

/** Register a real implementation. Called once, from the owning feature. */
export function registerProvider(id: ProviderId, provider: ConnectableProvider): void {
  registry.set(id, provider);
}

/** Test/reset hook. Not for production code paths. */
export function clearProviderRegistry(): void {
  registry.clear();
}

/** True when a feature has supplied a real implementation for this provider. */
export function isProviderRegistered(id: ProviderId): boolean {
  return registry.has(id);
}

/**
 * An honest placeholder. Every method resolves to `unavailable('not_connected')`.
 * It performs no I/O and returns no data.
 */
function unregisteredProvider(id: ProviderId): ConnectableProvider {
  const notConnected = <T>(): Promise<DataState<T>> =>
    Promise.resolve(unavailable('not_connected', NOT_CONNECTED_MESSAGE));

  return {
    id,
    displayName: DISPLAY_NAMES[id],
    getConnection: () => notConnected<ConnectionInfo>(),
    connect: () => notConnected<ConnectionInfo>(),
    disconnect: () => notConnected<void>(),
  };
}

/**
 * Always returns something usable. Screens call this and render whatever state
 * comes back - they never branch on whether an integration "exists yet".
 */
export function getProvider(id: ProviderId): ConnectableProvider {
  return registry.get(id) ?? unregisteredProvider(id);
}

/** Every provider the product knows about, in the order the UI lists them. */
export const ALL_PROVIDER_IDS: readonly ProviderId[] = [
  'google_business',
  'instagram',
  'facebook',
  'linkedin',
] as const;

export function getProviderDisplayName(id: ProviderId): string {
  return registry.get(id)?.displayName ?? DISPLAY_NAMES[id];
}
